			<footer id="footer">
				<nav>
					<ul>
						<li><a id="about-global-stories" href="<?php echo $this->url(array('action' => 'about-global-stories'),'action',true,false); ?>">About Global Stories</a></li>
						<li><a id="contact" href="<?php echo $this->url(array('action' => 'contact'),'action',true,false); ?>">Contact</a></li>
						<li><a id="suggest-story" href="<?php echo $this->i18n->t('footer_menu.suggest_story_href'); ?>">Suggest a story</a></li>
						<li><a id="terms-of-usage" href="<?php echo $this->url(array('action' => 'terms-of-usage'),'action',true,false); ?>">Terms of usage</a></li>
						<li><a id="privacy-policy" href="<?php echo $this->url(array('action' => 'privacy-policy'),'action',true,false); ?>">Privacy Policy</a></li>						
						<li><a id="report-broken-story" href="<?php echo $this->i18n->t('footer_menu.report_story_href'); ?>">Report broken story?</a></li>
						<li>Content not owned by global stories</li>
					</ul>
					<a id="back-to-story" href="">Back to Story</a>
				</nav>
			</footer>
			<!-- / footer -->
