<script type="text/javascript">
    var location_list_params = {};
    location_list_params['continent'] = {type:'select',model: 'Continent',method: 'getContinents',name: 'continent',first_label: '<?php echo $this->i18n->t('select.continent'); ?>',selected: '<?php echo @$this->form['continent']; ?>',onComplete: 'continent_change'};
    location_list_params['country'] = {type:'select',model: 'Country',method: 'getCountries',name: 'country',first_label: '<?php echo $this->i18n->t('select.contry'); ?>',selected: '<?php echo @$this->form['country']; ?>',onComplete: 'country_change'};
    location_list_params['city'] = {type:'select',model: 'City',method: 'getCities',name: 'city',first_label: '<?php echo $this->i18n->t('select.city'); ?>',selected: '<?php echo @$this->form['city']; ?>'};
</script>

<div id="content_page" class="page_wrapper<?php echo (!is_null($this->fancybox)) ? ' fancybox_page' : ''; ?>">
    <div class="content_inner">
        <h2><?php echo ($this->form['id'] > 0) ? $this->i18n->t($this->form['type'].'.edit') : $this->i18n->t($this->form['type'].'.add'); ?></h2>
        <div class="content_form">
            <form name="<?php echo $this->form['type']; ?>" action="<?php echo $this->url(array('content_type' => $this->form['type'],'content_action' => 'save','params' => http_build_query($this->form['params'])),'admin_content',true,false); ?>" method="POST">
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('form.name'); ?>:</div>
                <div class="form_value"><input type="text" name="name" value ="<?php echo htmlentities(@$this->form['name']); ?>" /></div>
                <div class="clear"></div>
            </div>
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('content.type_continent'); ?>:</div>
                <div id="continent" class="form_value"></div>
                <div class="clear"></div>
            </div>     
            <div class="form_row<?php echo ($this->form['id'] > 0) ? '' : ' hidden'; ?>">
                <div class="form_label"><?php echo $this->i18n->t('content.type_country'); ?>:</div>
                <div id="country" class="form_value"></div>
                <div class="clear"></div>
            </div>
            <div class="form_row<?php echo ($this->form['id'] > 0) ? '' : ' hidden'; ?>">
                <div class="form_label"><?php echo $this->i18n->t('content.type_city'); ?>:</div>
                <div id="city" class="form_value"></div>
                <div class="clear"></div>
            </div>    
            <div class="form_row submit_row">
                <div class="form_submit"><a class="btn primary large submit_button"><?php echo (@$this->form['id'] > 0) ? $this->i18n->t('form.save') : $this->i18n->t('form.add'); ?></a></div>
                <div class="form_validate_error"></div>
                <div class="clear"></div>     
            </div>
            <input type="hidden" name="id" value="<?php echo $this->form['id']; ?>" />
            </form>
        </div>    
    </div>
</div>
<script type="text/javascript">
    var generate_list_url = '<?php echo $this->url(array('action' => 'generate-list','controller' => 'ajax'),'action',true,false); ?>';
   
    $(document).ready(function(){
        <?php if ($this->form['id'] > 0): ?>
        location_list_params['country']['params'] = {continent: '<?php echo $this->form['continent']; ?>'}
        location_list_params['city']['params'] = {country: '<?php echo $this->form['country']; ?>'}
        
        $.each(location_list_params,function(k,v){
            generate_list(generate_list_url,k,v);
        });
        <?php else: ?>
        generate_list(generate_list_url,'continent',location_list_params['continent']);
        <?php endif; ?>
    });
</script>    
<?php echo $this->render('admin/sumbit_button_handler.phtml'); ?>
