<script type="text/javascript">
    
    var user_list_params = {};
    
    user_list_params['producer'] = {type:'select',model: 'Producer',method: 'getProducers',name: 'producer',selected: '<?php echo @$this->form['producer']; ?>'};

</script>

<div id="content_page" class="page_wrapper">
    <div class="content_inner">
        <h2><?php echo ($this->form['id'] > 0) ? $this->i18n->t($this->form['type'].'.edit') : $this->i18n->t($this->form['type'].'.add'); ?></h2>
        <div class="content_form">
            <form name="<?php echo $this->form['type']; ?>" action="<?php echo $this->url(array('content_type' => $this->form['type'],'content_action' => 'save','params' => http_build_query($this->form['params'])),'admin_content',true,false); ?>" method="POST">
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('user.user_type'); ?>:</div>
                <div class="form_value">
                		<select name="user_type">
                			<?php foreach ($this->user_types as $user_type): ?>
                			<option value="<?php echo $user_type['id']; ?>"<?php echo (@$this->form['user_type'] == $user_type['id']) ? ' selected="selected"' : ''; ?>><?php echo $this->i18n->t('user_type.'.$user_type['name']); ?></option>
                			<?php endforeach; ?>
                		</select>
                	</div>
                	<div class="clear"></div>
            </div>
            <div id="producer_row" class="form_row<?php echo (@$this->form['user_type'] != 2) ? ' hidden': ''; ?>">
                <div class="form_label"><?php echo $this->i18n->t('content.type_producer'); ?>:</div>
                <div id="producer" class="form_value"></div>
                <div class="clear"></div>
            </div>
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('form.name'); ?>:</div>
                <div class="form_value"><input type="text" name="name" value ="<?php echo htmlentities(@$this->form['name']); ?>" /></div>
                <div class="clear"></div>
            </div>
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('user.username'); ?>:</div>
                <div class="form_value"><input type="text" name="username" value ="<?php echo htmlentities(@$this->form['username']); ?>" /></div>
                <div class="clear"></div>
            </div> 
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('user.password'); ?>:</div>
                <div class="form_value"><input type="password" name="password" value ="" /></div>
                <div class="clear"></div>
            </div>  
            <div class="form_row">
                <div class="form_label"><?php echo $this->i18n->t('user.password_repeat'); ?>:</div>
                <div class="form_value"><input type="password" name="password_repeat" value ="" /></div>
                <div class="clear"></div>
            </div> 
            <div class="form_row submit_row">
                <div class="form_submit"><a class="btn primary large submit_button"><?php echo (@$this->form['id'] > 0) ? $this->i18n->t('form.save') : $this->i18n->t('form.add'); ?></a></div>
                <div class="form_validate_error"></div>
                <div class="clear"></div>     
            </div>
            <input type="hidden" name="id" value="<?php echo $this->form['id']; ?>" />
            </form>
        </div>    
    </div>
</div>

<script type="text/javascript">

	$(document).ready(function(){
        $.each(user_list_params,function(k,v){
            generate_list('<?php echo $this->url(array('action' => 'generate-list','controller' => 'ajax'),'action',true,false); ?>',k,v);
        });
        
		$("select[name=user_type]").bind('change',function(){
			if ($(this).val() != 2) {
				$("#producer_row").addClass('hidden');
			}
			else {
				$("#producer_row").removeClass('hidden');
			}
		});
	});

</script>

<?php echo $this->render('admin/sumbit_button_handler.phtml'); ?>