       		<form name="list_form" action="" method="POST">
       		<table class="bordered-table zebra-striped">
				<thead>
					<tr id="table_headers">
		       			<th><input id="check_all" class="nomargin" type="checkbox" name="check_all" value="" /></th>
		       			<th><?php echo $this->i18n->t('form.sharp'); ?></th>
		       			<th id="order_name" class="order_cell header"><?php echo $this->i18n->t('form.title'); ?></th>
		       			<th id="order_state" class="order_cell header"><?php echo $this->i18n->t('form.state'); ?></th>
		       			<th id="order_id" class="order_cell header"><?php echo $this->i18n->t('form.id'); ?></th>
		       			<th id="order_date_updated" class="order_cell header"><?php echo $this->i18n->t('form.date'); ?></th>
		       			<th id="order_author" class="order_cell header"><?php echo $this->i18n->t('form.author'); ?></th>
		       			<th id="order_last_edited_by" class="order_cell header"><?php echo $this->i18n->t('form.last_edited_by'); ?></th>
					</tr>
				</thead>
				<tbody>
					<?php $i = 0;?>
		            <?php foreach ($this->stories as $story): $i++; ?>
		            <tr>
		            	<td><input class="nomargin check_list" type="checkbox" name="check_list[<?php echo $story['id']; ?>]" value="" /></td>
		            	<td><?php echo $i; ?></td>
		            	<td><a href="<?php echo $this->url(array('content_action' => 'edit','content_type' => 'story','params' => http_build_query(array('id' => $story['id']))),'admin_content',true,false); ?>"><?php echo $story['name']; ?></a></td>
		            	<td><?php echo ($story['state'] > 0) ? $this->i18n->t('form.state_active') : $this->i18n->t('form.state_not_active'); ?></td>
		            	<td><?php echo $story['id']; ?></td>
		            	<td><?php echo date("d/m/Y H:i:s",strtotime($story['date_updated'])); ?></td>
		            	<td><?php echo $story['user']; ?></td>
		            	<td><?php echo $story['updated_by']; ?></td>
		            </tr>   
		            <?php endforeach; ?>
				</tbody>
       		</table>
       		</form>
       		<?php echo $this->paginationControl($this->stories, 'Sliding', 'pagination-ajax.phtml',array('i18n' => $this->i18n,'callback' => 'load_list_table')); ?>