<div id="overlay-demo" class="overlay-text">
	<h2>About Global Stories</h2>
	<div class="content">
		<p>The Global Stories project is a way of showing the world that people:-</p>

		<p>- care<br />- want to learn<br />- are making a difference every day</p>

		<p>about the world we live in.</p>

		<p>This website was designed with the belief that by:-</p>

		<p>- showing a diversity of viewpoints<br />- letting the audience become editors<br />- share their passion to the rest of their community</p>

		<p>that real change can happen.</p>

		<p>We do not imply any relationship with any of the content providers on the site by linking to it.</p>
	</div>
</div>
<?php die(); ?>