<div id="overlay-demo" class="overlay-text">
	<h2>Privacy Policy</h2>
	<div class="content">

		<p style="color:#FFFFFF">Privacy Policy</p>
		
		<p>We are committed to safeguarding the privacy of our website visitors; this policy sets out how we will treat your personal information.</p>
		
		<p>Our website uses cookies. By using our website and agreeing to this policy, you consent to our use of cookies in accordance with the terms of this policy.</p>
		
		<p>The data controller responsible in respect of the information collected on this website is <span style="color:#FFFFFF">Global Stories Ltd</span></p>

		<p>Registration number <span style="color:#FFFFFF">Z302145X</span> in accordance with the <span style="color:#FFFFFF">Data Protection Act 1998.</span></p>

		<p style="color:#FFFFFF">(1) What information do we collect?</p>
		
		<p>We may collect, store and use the following kinds of personal information:</p>
		
		<p>(a) information about your computer and about your visits to and use of this website including your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views, website navigation);</p>
		
		<p>(b) information that you provide to us through connecting with Facebook</p>
		
		<p>(c) any other information that you choose to send to us; and</p>
		
		<p>(d) <span style="font-style:italic">other information.</span></p>
		
		<p style="color:#FFFFFF">(2) Cookies</p>
		
		<p>A cookie consists of information sent by a web server to a web browser, and stored by the browser. The information is then sent back to the server each time the browser requests a page from the server. This enables the web server to identify and track the web browser.</p>
		
		<p>We may use both "session" cookies and "persistent" cookies on the website.</p>
		
		<p>We will use the session cookies to: keep track of you whilst you navigate the website.</p>
		
		<p>We will use the persistent cookies to: enable our website to recognise you when you visit.</p>
		
		<p>Session cookies will be deleted from your computer when you close your browser.</p>
		
		<p>Persistent cookies will remain stored on your computer until deleted, or until they reach a specified expiry date.</p>
		
		<p>We use Google Analytics to analyse the use of this website. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users' computers. The information generated relating to our website is used to create reports about the use of the website.</p>
		
		<p>Google will store this information. Google's privacy policy is available at: http://www.google.com/privacypolicy.html</p>
			
		<p>Most browsers allow you to reject all cookies, whilst some browsers allow you to reject just third party cookies. For example, in Internet Explorer you can refuse all cookies by clicking "Tools", "Internet Options", "Privacy", and selecting "Block all cookies" using the sliding selector. Blocking all cookies will, however, have a negative impact upon the usability of many websites, including this one.</p>
		
		<p style="color:#FFFFFF">(3) Using your personal information</p>
				
		<p>Personal information submitted to us via this website will be used for the purposes specified in this privacy policy or in relevant parts of the website.</p>
				
		<p>We may use your personal information to:</p>
				
		<p>(a) administer the website;</p>
				
		<p>(b) improve your browsing experience by personalising the website;</p>
				
		<p>(c) enable your use of the services available on the website;</p>
				
		<p>(d) send you general (non-marketing) commercial communications;</p>
				
		<p>(e) send you email notifications which you have specifically requested;</p>
				
		<p>(f) send to you our newsletter and other marketing communications relating to our business.</p>
				
		<p>(g) provide third parties with statistical information about our users as a demographic group BUT not your individual information.</p>
				
		<p>(h) deal with enquiries and complaints made by or about you relating to the website; and</p>
				
		<p>(i) <span style="font-style:italic">other uses.</span></p>
				
		<p>Where in the future you submit personal information for publication on our website, we will publish and otherwise use that information in accordance with the license you grant to us.</p>
				
		<p>We will <span style="color:#FFFFFF; font-style:italic;">NOT</span> without your express consent provide your personal information to any third parties for the purpose of direct marketing.</p>
				
		<p style="color:#FFFFFF">(4) Disclosures</p>
				
		<p>We may disclose information about you to any of our employees, officers, agents, suppliers or subcontractors in so far as reasonably necessary for the purposes as set out in this privacy policy.</p>
				
		<p>In addition, we may disclose your personal information:</p>
				
		<p>(a) to the extent that we are required to do so by law;</p>
				
		<p>(b) in connection with any legal proceedings or prospective legal proceedings;</p>
				
		<p>(c) in order to establish, exercise or defend our legal rights (including providing information to others for the purposes of fraud prevention and reducing credit risk);</p>
				
		<p>(d) to the purchaser (or prospective purchaser) of any business or asset which we are (or are contemplating) selling; and</p>
		
		<p>(e) to any person who we reasonably believe may apply to a court or other competent authority for disclosure of that personal information where, in our reasonable opinion, such court or authority would be reasonably likely to order disclosure of that personal information.</p>
				
		<p style="color:#FFFFFF">(5) International data transfers</p>
				
		<p>Information that we collect may be stored and processed in and transferred between any of the countries in which we operate in order to enable us to use the information in accordance with this privacy policy.</p>
				
		<p>Information which you provide may be transferred to countries, including the <span style="font-style:italic">other countries</span> which do not have data protection laws equivalent to those in force in the European Economic Area.</p>
				
		<p>In addition, personal information that you submit for publication on the website will be published on the internet and may be available, via the internet, around the world. We cannot prevent the use or misuse of such information by others.</p>
				
		<p>You expressly agree to such transfers of personal information.</p>
				
		<p style="color:#FFFFFF">(6) Security of your personal information</p>
				
		<p>We will take reasonable technical and organisational precautions to prevent the loss, misuse or alteration of your personal information.</p>
				
		<p>Of course, data transmission over the internet is inherently insecure, and we cannot guarantee the security of data sent over the internet.</p>
				
		<p style="color:#FFFFFF">(7) Policy amendments</p>
				
		<p>We may update this privacy policy from time-to-time by posting a new version on our website. You should check this page occasionally to ensure you are happy with any changes.</p>
				
		<p style="color:#FFFFFF">(8) Third party websites</p>
				
		<p>The website contains links to other websites. We are not responsible for the privacy policies or practices of third party websites.</p>
				
		<p style="color:#FFFFFF">(9) Contact</p>
				
		<p>If you have any questions about this privacy policy or our treatment of your personal information, please write to us by email to info@globalstories.org or by post to:</p>
				
		<p>Global Stories Ltd<br />First Floor</p>
				
		<p>51 Hoxton Square<br />London<br />N1 6PB</p>
				
		<p>United Kingdom</p>
																	
	</div>
</div>
<?php die(); ?>
