<div id="overlay-demo" class="overlay-text">
	<h2>Terms of usage</h2>
	<div class="content">

		<p style="color:#FFFFFF">(1) Introduction</p>

		<p>These terms and conditions govern your use of our website; by using our website, you accept these terms and conditions in full. If you disagree with these terms and conditions or any part of these terms and conditions, you must not use our website.</p>

		<p>Our website uses cookies. By using our website and agreeing to these terms and conditions, you consent to our use of cookies in accordance with the terms of our privacy policy/cookies policy.</p>

		<p style="color:#FFFFFF">(3) Licence to use website</p>

		<p>Unless otherwise stated, we own the intellectual property rights in the website. Subject to the licence below, all these intellectual property rights are reserved.</p>

		<p>You must also adhere to the terms and conditions of original content producer.</p>

		<p>You may view, download for caching purposes only, and print pages from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms and conditions.</p>

		<p>You must not:</p>

		<p style="color:#FFFFFF">(a) sell, rent or sub-license material from the website;</p>

		<p style="color:#FFFFFF">(b) edit or otherwise modify any material on the website;</p>

		<p style="color:#FFFFFF">(c) reproduce, duplicate, copy or otherwise exploit Global Stories material on the website for a commercial purpose without our consent;</p>

		<p style="color:#FFFFFF">(d) contravene the terms and conditions of the original content producer on the website;</p>

		<p style="color:#FFFFFF">(4) Acceptable use</p>

		<p>You must not use our website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</p>

		<p>You must not use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.</p>

		<p>You must not conduct any systematic or automated data collection activities including without limitation scraping, data mining, data extraction and data harvesting on or in relation to our website without our express written consent.</p>

		<p>You must not use our website to transmit or send unsolicited commercial communications.</p>

		<p>You must not use our website for any purposes related to marketing without our express written consent.</p>

		<p style="color:#FFFFFF">(5) Restricted access</p>

		<p>We reserve the right to restrict access to areas of our website, or indeed our whole website, at our discretion.</p>

		<p style="color:#FFFFFF">(6) Linked or embedded Content not owned by Global Stories Ltd</p>

		<p>Global Stories Ltd does not own the content unless explicitly stated therefore you will abide by the terms and conditions as set out by the original producer of the content.</p>

		<p style="color:#FFFFFF">(7) Limited warranties</p>

		<p>We do not warrant the completeness or accuracy of the information published on this website; nor do we commit to ensuring that the website remains available or that the material on the website is kept up-to-date.</p>

		<p>To the maximum extent permitted by applicable law we exclude all representations, warranties and conditions relating to this website and the use of this website (including, without limitation, any warranties implied by law of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill).</p>

		<p style="color:#FFFFFF">(8) Limitations and exclusions of liability</p>

		<p>Nothing in these terms and conditions will: (a) limit or exclude our or your liability for death or personal injury resulting from negligence; (b) limit or exclude our or your liability for fraud or fraudulent misrepresentation; (c) limit any of our or your liabilities in any way that is not permitted under applicable law; or (d) exclude any of our or your liabilities that may not be excluded under applicable law.</p>

		<p>The limitations and exclusions of liability set out in this Section and elsewhere in these terms and conditions: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the terms and conditions or in relation to the subject matter of the terms and conditions, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.</p>

		<p>To the extent that the website and the information and services on the website are provided free-of-charge, we will not be liable for any loss or damage of any nature.</p>

		<p>We will not be liable to you in respect of any losses arising out of any event or events beyond our reasonable control.</p>

		<p>We will not be liable to you in respect of any loss or corruption of any data, database or software.</p>

		<p style="color:#FFFFFF">(9) Indemnity</p>

		<p>You hereby indemnify us and undertake to keep us indemnified against any losses, damages, costs, liabilities and expenses (including without limitation legal expenses and any amounts paid by us to a third party in settlement of a claim or dispute on the advice of our legal advisers) incurred or suffered by us arising out of any breach by you of any provision of these terms and conditions.</p>

		<p style="color:#FFFFFF">(10) Breaches of these terms and conditions</p>

		<p>Without prejudice to our other rights under these terms and conditions, if you breach these terms and conditions in any way, we may take such action as we deem appropriate to deal with the breach, including suspending your access to the website, prohibiting you from accessing the website, blocking computers using your IP address from accessing the website, contacting your internet service provider to request that they block your access to the website and/or bringing court proceedings against you.</p>

		<p style="color:#FFFFFF">(11) Variation</p>

		<p>We may revise these terms and conditions from time-to-time. Revised terms and conditions will apply to the use of our website from the date of the publication of the revised terms and conditions on our website. Please check this page regularly to ensure you are familiar with the current version.</p>

		<p style="color:#FFFFFF">(12) Assignment</p>

		<p>We may transfer, sub-contract or otherwise deal with our rights and/or obligations under these terms and conditions without notifying you or obtaining your consent.</p>

		<p>You may not transfer, sub-contract or otherwise deal with your rights and/or obligations under these terms and conditions.</p>

		<p style="color:#FFFFFF">(13) Severability</p>

		<p>If a provision of these terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect. If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.</p>

		<p style="color:#FFFFFF">(14) Exclusion of third party rights</p>

		<p>These terms and conditions are for the benefit of you and us, and are not intended to benefit any third party or be enforceable by any third party. The exercise of our and your rights in relation to these terms and conditions is not subject to the consent of any third party.</p>

		<p style="color:#FFFFFF">(15) Entire agreement</p>

		<p>These terms and conditions constitute the entire agreement between you and us in relation to your use of our website, and supersede all previous agreements in respect of your use of this website.</p>

		<p style="color:#FFFFFF">(16) Law and jurisdiction</p>

		<p>These terms and conditions will be governed by and construed in accordance with English law, and any disputes relating to these terms and conditions will be subject to the non-exclusive jurisdiction of the courts of England and Wales.</p>

		<p style="color:#FFFFFF">(17) Our details</p>

		<p>The full name of our company is Global Stories Ltd.</p>

		<p>We are registered in England &amp; Wales under registration number 07098972</p>

		<p>Our address is:-</p>

		<p>Global Stories First Floor 51 Hoxton Square London N1 6PB</p>

	</div>
</div>
<?php die(); ?>