<?php
	$cache_expire = 60*60*24*365;
	header("Content-type: text/html; charset=UTF-8");  
 	header("Pragma: public");
 	header("Cache-Control: max-age=".$cache_expire);
 	header('Expires: ' . gmdate('D, d M Y H:i:s', time()+$cache_expire) . ' GMT');
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->render('blocks/head.phtml'); ?>
		<script type="text/javascript">
		
			if (swfobject.hasFlashPlayerVersion('10.0.0')) {
				window.location = '<?php echo $this->url(array(),'action',true,false); ?>';
			}
		
		</script>
	</head>
	<body class="page-noflash">
		<div id="page">
			<div class="section-inner">
				<div id="message-noflash">
					<div class="section">
						<h1><a href="#">GlobalStories</a></h1>
						<p>Global Stories requires flash to work until funds are made available to develop a version for iOS.</p>
						<a target="_blank" href="http://get.adobe.com/flashplayer/" rel="external" class="get-flash">Get the flash player</a>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
		
			var _gaq = _gaq || [];
				_gaq.push(['_setAccount', 'UA-28299261-1']);
			  	_gaq.push(['_setDomainName', '.globalstories.org']);
			  	_gaq.push(['_trackPageview']);
			  	
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			  	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			  	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
			  	  
		</script>
	</body>
</html>
